name: Build and package RoBERTa-sequencing to Dockerhub

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Set auto-install of extensions
        run: az config set extension.use_dynamic_install=yes_without_prompt

      - name: Attach workspace
        run: az ml folder attach -w "ml-ws" -g "practical-mlops"

      - name: Retrieve the model
        run: az ml model download -t "." --model-id "robertasequence:1"

      - name: Build flask-app container
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: alfredodeza/flask-roberta:latest
