name: Build and package RoBERTa-sequencing to Dockerhub

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Authenticate with Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set auto-install of extensions
        run: az config set extension.use_dynamic_install=yes_without_prompt

      - name: Attach workspace
        run: az configure --defaults workspace="ml-ws" group="practical-mlops"

      - name: Retrieve the model
        run:  az ml model download -t "." --model-id "robertasequence:1"

      - name: Build flask-app container
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: alfredodeza/flask-roberta:latest
